name: unity-xcode-builder
description: A GitHub Action to build and archive Unity exported xcode projects.
branding:
  icon: 'command'
  color: 'blue'
inputs:
  project-path:
    description: The directory that contains the exported xcode project from Unity.
    required: true
  app-store-connect-key-id:
    description: The key ID of the App Store Connect API key.
    required: true
  app-store-connect-issuer-id:
    description: The issuer ID of the App Store Connect API key.
    required: true
  certificate:
    description: Exported signing certificate.p12 encoded as base64 string.
    required: true
  certificate-password:
    description: The password for the exported `certificate`.
    required: true
  team-id:
    description: The team ID to use for signing the Xcode project. Overrides the value in the exported Unity project.
    required: false
  bundle-id:
    description: The bundle ID of the Xcode project. Overrides the value in the exported Unity project.
    required: false
  configuration:
    description: The configuration to build the Xcode project with.
    required: false
    default: 'Release'
  xcscheme:
    description: The path to the xcscheme to build the Xcode project with. Overrides the value in the exported Unity project.
    required: false
  provisioning-profile:
    description: The provisioning profile to use for signing the Xcode project as base64 string.
    required: false
  provisioning-profile-name:
    description: The name of the provisioning profile file, including the type to use for signing the Xcode project.
    required: false
  export-option:
    description: The export option to use for archiving the Xcode project. Can be one of 'app-store', 'ad-hoc', 'package', 'enterprise', 'development', 'developer-id', 'mac-application'.
    required: false
    default: 'development'
outputs:
  archive:
    description: The path to the generated archive.
  executable:
    description: The path to the generated executable.
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
